name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++

    - name: Configure main project
      run: cmake -H. -B_build -DBUILD_TESTS=OFF

    - name: Build main project
      run: cmake --build _build

    - name: Configure banking (without tests)
      run: |
        cd banking
        cmake -H. -B_build
        cd ..

