name: Coveralls

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ python3-pip
        pip3 install cpp-coveralls

    - name: Configure and build with coverage
      run: |
        cd banking
        cmake -H. -B_build -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="--coverage -fprofile-arcs -ftest-coverage"
        cmake --build _build
        cd _build
        ./banking_check
        cd ../..

    - name: Upload to Coveralls
      run: |
        cd banking
        coveralls --exclude _build --exclude tests --exclude /usr/include --gcov-options '\-lp'
        cd ..
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
